.TH "rb_header_size" "3" " 9 February 2018 (v1.0.0)" "bofc.pl"
.SH NAME
.PP
.B rb_header_size
- read size of
.B rb
header in bytes.
.SH SYNOPSIS
.PP
.B "#include <librb.h>"
.PP
.B size_t rb_header_size(void);
.SH RETURN VALUE
.PP
Function returns size of iternal struct with information about buffer.
Size of the buffer with data is not included.
.SH SEE ALSO
.PP
.BR rb_overview (7),
.BR rb_new (3),
.BR rb_init (3),
.BR rb_destroy (3),
.BR rb_cleanup (3),
.BR rb_discard (3),
.BR rb_stop (3),
.BR rb_stop_signal (3),
.BR rb_read (3),
.BR rb_recv (3),
.BR rb_write (3),
.BR rb_send (3),
.BR rb_posix_read (3),
.BR rb_posix_recv (3),
.BR rb_posix_write (3),
.BR rb_posix_send (3),
.BR rb_clear (3),
.BR rb_count (3),
.BR rb_space (3),
.BR rb_version (3)
