.TH "rb_space" "3" "25 January 2018 (v2.1.2)" "bofc.pl"
.SH NAME
.PP
.BR rb_space,
.B rb_count
- get count information for ring buffer
.SH SYNOPSIS
.PP
.BI "#include <librb.h>"
.PP
.BI "size_t rb_count(struct rb *" rb ");"
.br
.BI "size_t rb_space(struct rb *" rb ");"
.SH RETURN VALUES
.PP
.BR rb_count (3)
returns number of
.B elements
that are currently stored in buffer, and
.BR rb_space (3)
returns number of how many
.B elements
you can put on the buffer.
.SH SEE ALSO
.PP
.BR rb_overview (7),
.BR rb_new (3),
.BR rb_destroy (3),
.BR rb_stop (3),
.BR rb_read (3),
.BR rb_recv (3),
.BR rb_write (3),
.BR rb_send (3),
.BR rb_clear (3),
.BR rb_version (3)
