.TH "rb_space" "3" " 9 February 2018 (v1.0.0)" "bofc.pl"
.SH NAME
.PP
.BR rb_space,
.B rb_count
- get count information for ring buffer
.SH SYNOPSIS
.PP
.BI "#include <librb.h>"
.PP
.BI "long rb_count(struct rb *" rb ");"
.br
.BI "long rb_space(struct rb *" rb ");"
.SH RETURN VALUES
.PP
.BR rb_count (3)
returns number of
.B elements
that are currently stored in buffer, and
.BR rb_space (3)
returns number of how many
.B elements
you can put on the buffer.
.SH ERRORS
.PP
.TP
.B EINVAL
Passed
.I rb
object is invalid.
.SH SEE ALSO
.PP
.BR rb_overview (7),
.BR rb_new (3),
.BR rb_init (3),
.BR rb_destroy (3),
.BR rb_cleanup (3),
.BR rb_discard (3),
.BR rb_stop (3),
.BR rb_stop_signal (3),
.BR rb_read (3),
.BR rb_recv (3),
.BR rb_write (3),
.BR rb_send (3),
.BR rb_posix_read (3),
.BR rb_posix_recv (3),
.BR rb_posix_write (3),
.BR rb_posix_send (3),
.BR rb_clear (3),
.BR rb_header_size (3),
.BR rb_array_size (3),
.BR rb_version (3)
