.TH "rb_version" "3" " 5 February 2018 (v3.0.0)" "bofc.pl"
.SH NAME
.PP
.B rb_version
- queries for library version
.SH SYNOPSIS
.PP
.BI "#include <librb.h>"
.PP
.BI "const char *rb_version(char *" major ", char *" minor ", char *" patch ");"
.SH DESCRIPTION
.PP
Function returns library version.
Each of input parameters should be at least 4 bytes long.
If any of the input parameters is NULL function won't store anything and will
just return version as string.
.B librb
uses semantic versioning:
.TP
.I major
This will be incremented when changes non backward compatible changes are made
to either ABI or API.
.TP
.I minor
This will incremented when backward compatible changes are introduced (like new
features) to either ABI or API.
.TP
.I patch
This is incremented when patch is introduced without changing neither ABI nor
API.
.SH RETURN VALUES
.PP
Function returns pointer to statically allocated string with full version, like
"1.2.6"
.SH SEE ALSO
.PP
.BR rb_overview (7),
.BR rb_new (3),
.BR rb_destroy (3),
.BR rb_discard (3),
.BR rb_stop (3),
.BR rb_read (3),
.BR rb_recv (3),
.BR rb_write (3),
.BR rb_send (3),
.BR rb_clear (3),
.BR rb_count (3),
.BR rb_space (3),
